In [1]:
import numpy as np

In [3]:
np1=np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [5]:
# 2d 
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [9]:
# to get individual elements
for x in np2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [11]:
# 3d array 
np3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [15]:
for x in np3:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [17]:
for x in np3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
# nditer()
for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [21]:
for x in np.nditer(np1):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [23]:
for x in np.nditer(np2):
    print(x)

1
2
3
4
5
6
7
8
9
10
