In [1]:
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [3]:
print(list1[0])

1


In [5]:
list2=["Arundhati",41,list1,True]
print(list2)

['Arundhati', 41, [1, 2, 3, 4, 5], True]


In [7]:
import numpy as np

In [9]:
np1=np.array([0,1,2,3,4,5])
print(np1)

[0 1 2 3 4 5]


In [11]:
np1.shape

(6,)

In [13]:
np2=np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
np3=np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


In [17]:
np4=np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
np5=np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
np6=np.full((10,6),0)
print(np6)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [29]:
np7=np.full((2,10),6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [31]:
# convert python list to numpy
my_list=[1,2,3,4,5]
np8=np.array(my_list)
print(np8)

[1 2 3 4 5]


In [33]:
print(np8[0])

1
