In [1]:
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
# shape of numpy array
print(np1.shape)

(12,)


In [5]:
# 2d array
np2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
# shape
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [7]:
# reshape
np3=np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [9]:
# reshape to 3d 
np4=np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [13]:
np5=np1.reshape(3,2,2)
print(np5)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [15]:
np6=np1.reshape(2,2,3)
print(np6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
np7=np4.reshape(-1)
print(np7)
print(np7.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
