In [1]:
import numpy as np

In [5]:
np1=np.array([6,7,4,9,0,2,1])
print(np1)
print(np.sort(np1))

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]


In [7]:
# alphabetical
np2=np.array(["John","Tina","Aron","Zed"])
print(np2)
print(np.sort(np2))

['John' 'Tina' 'Aron' 'Zed']
['Aron' 'John' 'Tina' 'Zed']


In [9]:
# booleans
np3=np.array([True,False,False,True])
print(np3)
print(np.sort(np3))

[ True False False  True]
[False False  True  True]


In [13]:
# copy is changed not the actual array
print(np1)
print(np.sort(np1))
print(np1)

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[6 7 4 9 0 2 1]


In [15]:
# 2d
np4=np.array([[6,7,1,9],[8,3,5,0]])
print(np4)
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]
